spring:
  datasource:
    url: jdbc:postgresql://dpg-d3ehctripnbc73btoqsg-a:5432/mikami_gohan_postgres_stg
    username: mikami_gohan_postgres_stg_user
    password: PfocmMALnkZGmN2IrpMOH6TRsgDyFEwc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # テーブル自動生成・更新する場合
    show-sql: true      # SQLをログに出す場合
