spring:
#local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mikami_gohan
    username: postgres
    password: postgres
    
    thymeleaf: 
      encoding: UTF-8
      cache: false
    http:
      encoding.charset: UTF-8
      encoding.enabled: true
      encoding.force: true
    
server:
  port: 8081
  error.whitelabel.enabled: false  # デフォルト Error Page を無効化
  error.path: /error
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.mybatis: DEBUG
    com.example.mapper: DEBUG
    